### ISSUE TITLE
Not Specific Enough / Issue

### ISSUE THREAD

**Issue by Faiirx49** [LeehamsonThe3rd/raycastsuspensionwheel#1]
This suspension is very cool but I think you lack specifics on how to set it up. Should it be anchored? Welded?. What stats would be realisitic for the Attributes, what part should be used/chassis part in the .new() function. I believe if you sent a RBXL with a working/dummy chassis it would help a lot of people using this project.

I've had no success with this. 

Local script in Server Scripts
![image](https://user-images.githubusercontent.com/124215192/216186641-4ac74d65-dca4-4259-89bd-2b607e8cceea.png)

Wheel Attributes:
![image](https://user-images.githubusercontent.com/124215192/216186779-35e97892-25b7-4de4-b0d4-988a1a5712ba.png)

Not obviosuly working
![image](https://user-images.githubusercontent.com/124215192/216187147-f1e71b0c-5bae-4b49-bc49-03932feb1ad4.png)

**Comment by LeehamsonThe3rd** [comment]
An example place is now provided. Thank you for addressing this.
